### ISSUE TITLE
Further development of the platform

### ISSUE THREAD

**Issue by volanar** [Qolzam/ts-next#1]
Hello. I am very sad that the platform is not developing. But I have a business proposition. How can I contact You?

**Comment by Qolzam** [comment]
@volanar, sorry to hear that, but I get busy with another business project at the time I was developing UI for `Next.js`. It is why I made an **interruption** (little bit long 😞 ) to do business promise. 
Anyway I am open for new business but I am also happy if I can help you with open-source part. 
Here is my email: amir.gholzam@live.com
Let me know how I can help you.
Thank you 😉

**Comment by volanar** [comment]
I'm sorry I didn't notice your answer. I'll write to you tomorrow
